openapi: 3.1.0
info:
  title: Box Collaboration Whitelist Exempt Targets API
paths:
  /collaboration_whitelist_exempt_targets:
    get:
      summary: List users exempt from collaboration domain restrictions
      tags:
        - List
        - Users
        - Exempt
        - From
        - Collaboration
        - Domain
        - Restrictions
        - Collaboration_whitelist_exempt_targets
      description: |-
        Returns a list of users who have been exempt from the collaboration
        domain restrictions.
    post:
      summary: Create user exemption from collaboration domain restrictions
      tags:
        - Create
        - User
        - Exemption
        - From
        - Collaboration
        - Domain
        - Restrictions
        - Collaboration_whitelist_exempt_targets
      description: >-
        Exempts a user from the restrictions set out by the allowed list of
        domains

        for collaborations.
  /collaboration_whitelist_exempt_targets/{collaboration_whitelist_exempt_target_id}:
    get:
      summary: Get user exempt from collaboration domain restrictions
      tags:
        - Get
        - User
        - Exempt
        - From
        - Collaboration
        - Domain
        - Restrictions
        - Collaboration_whitelist_exempt_targets
        - Collaboration_whitelist_exempt_target_id
      description: |-
        Returns a users who has been exempt from the collaboration
        domain restrictions.
    delete:
      summary: Remove user from list of users exempt from domain restrictions
      tags:
        - Remove
        - User
        - From
        - List
        - Of
        - Users
        - Exempt
        - Domain
        - Restrictions
        - Collaboration_whitelist_exempt_targets
        - Collaboration_whitelist_exempt_target_id
      description: >-
        Removes a user's exemption from the restrictions set out by the allowed
        list

        of domains for col
