openapi: 3.1.0
info:
  title: Box Collaborations API
paths:
  /files/{file_id}/collaborations:
    get:
      summary: List file collaborations
      description: |-
        Retrieves a list of pending and active collaborations for a
        file. This returns all the users that have access to the file
        or have been invited to the file.
      tags:
        - List
        - File
        - Collaborations
        - Files
        - File_id
        - Collaborations
  /folders/{folder_id}/collaborations:
    get:
      summary: List folder collaborations
      description: |-
        Retrieves a list of pending and active collaborations for a
        folder. This returns all the users that have access to the folder
        or have been invited to the folder.
      tags:
        - List
        - Folder
        - Collaborations
        - Files
        - File_id
        - Collaborations
        - Folders
        - Folder_id
  /collaborations/{collaboration_id}:
    get:
      summary: Get collaboration
      tags:
        - Get
        - Collaboration
        - Files
        - File_id
        - Collaborations
        - Folders
        - Folder_id
        - Collaboration_id
      description: Retrieves a single collaboration.
    put:
      tags:
        - Update
        - Collaboration
        - Files
        - File_id
        - Collaborations
        - Folders
        - Folder_id
        - Collaboration_id
      summary: Update collaboration
      description: |-
        Updates a collaboration.
        Can be used to change the owner of an item, or to
        accept collaboration invites.
    delete:
      summary: Remove collaboration
      tags:
        - Remove
        - Collaboration
        - Files
        - File_id
        - Collaborations
        - Folders
        - Folder_id
        - Collaboration_id
      description: Deletes a single collaboration.
  /collaborations:
    get:
      summary: List pending collaborations
      tags:
        - List
        - Pending
        - Collaborations
        - Files
        - File_id
        - Collaborations
        - Folders
        - Folder_id
        - Collaboration_id
      description: Retrieves all pending collaboration invites for this user.
    post:
      tags:
        - Create
        - Collaboration
        - Files
        - File_id
        - Collaborations
        - Folders
        - Folder_id
        - Collaboration_id
      summary: Create collaboration
      description: |-
        Adds a collaboration for a single user or a single group to a file
        or folder.

        Collaborations can be created using email address, user IDs, or a
        group IDs.

        If a collaboration is being created with a group, access to
        this endpoint is dependent on the group's ability to be invited.

        If collaboration is in `pending` status, the following fields
        are redacted:
        - `login` and `name` are hidden if a collaboration was created
        using `user_id`,
        -  `name` is hidden if a collaboration was created using `login`.
  /groups/{group_id}/collaborations:
    get:
      summary: List group collaborations
      tags:
        - List
        - Group
        - Collaborations
        - Files
        - File_id
        - Collaborations
        - Folders
        - Folder_id
        - Collaboration_id
        - Groups
        - Group_id
      description: |-
        Retrieves all the collaborations for a group. The user
        must have admin permissions to inspect enterprise's groups.

        Each collaboration object has details on which files or
        folders the group has access to and wit
