openapi: 3.1.0
info:
  title: Box Device Pinners API
paths:
  /device_pinners/{device_pinner_id}:
    get:
      summary: Get device pin
      tags:
        - Get
        - Device
        - Pin
        - Device_pinners
        - Device_pinner_id
      description: Retrieves information about an individual device pin.
    delete:
      summary: Remove device pin
      tags:
        - Remove
        - Device
        - Pin
        - Device_pinners
        - Device_pinner_id
      description: Deletes an individual device pin.
  /enterprises/{enterprise_id}/device_pinners:
    get:
      summary: List enterprise device pins
      tags:
        - List
        - Enterprise
        - Device
        - Pins
        - Device_pinners
        - Device_pinner_id
        - Enterprises
        - Enterprise_id
      description: |-
        Retrieves all the device pins within an enterprise.

        The user must have admin privileges, and the application
        needs the "manage enterprise" scope to mak
