openapi: 3.1.0
info:
  title: Box File Version Retentions API
paths:
  /file_version_retentions:
    get:
      tags:
        - List
        - File
        - Version
        - Retentions
        - File_version_retentions
      summary: List file version retentions
      description: Retrieves all file version retentions for the given enterprise.
  /file_version_retentions/{file_version_retention_id}:
    get:
      tags:
        - Get
        - Retention
        - 'On'
        - File
        - File_version_retentions
        - File_version_retention_id
      summary: Get retention on file
      description: Returns information about a file versi
