openapi: 3.1.0
info:
  title: Box File Version Legal Holds API
paths:
  /file_version_legal_holds/{file_version_legal_hold_id}:
    get:
      summary: Get file version legal hold
      tags:
        - Get
        - File
        - Version
        - Legal
        - Hold
        - File_version_legal_holds
        - File_version_legal_hold_id
      description: |-
        Retrieves information about the legal hold policies
        assigned to a file version.
  /file_version_legal_holds:
    get:
      summary: List file version legal holds
      tags:
        - List
        - File
        - Version
        - Legal
        - Holds
        - File_version_legal_holds
        - File_version_legal_hold_id
      description: >-
        Get a list of file versions on legal hold for a legal hold

        assignment.


        Due to ongoing re-architecture efforts this API might not return all
        file

        versions for this policy ID.


        Instead, this API will only return file versions held in the legacy

        architecture. Two new endpoints will available to request any file
        versions

        held in the new architecture.


        For file versions held in the new architecture, the `GET

        /legal_hold_policy_assignments/:id/file_versions_on_hold` API can be
        used to

        return all past file versions available for this policy assignment, and
        the

        `GET /legal_hold_policy_assignments/:id/files_on_hold` API can be used
        to

        return any current (latest) versions of a file under legal hold.


        The `GET /legal_hold_policy_assignments?policy_id={id}` API can be used
        to

        find a list of policy assignments for a given policy ID.


        Once the re-architecture is completed this API will be
