openapi: 3.1.0
info:
  title: Box Group Memberships API
paths:
  /group_memberships:
    post:
      summary: Add user to group
      tags:
        - Add
        - User
        - To
        - Group
        - Group_memberships
      description: |-
        Creates a group membership. Only users with
        admin-level permissions will be able to use this API.
  /group_memberships/{group_membership_id}:
    get:
      summary: Get group membership
      tags:
        - Get
        - Group
        - Membership
        - Group_memberships
        - Group_membership_id
      description: |-
        Retrieves a specific group membership. Only admins of this
        group or users with admin-level permissions will be able to
        use this API.
    put:
      summary: Update group membership
      tags:
        - Update
        - Group
        - Membership
        - Group_memberships
        - Group_membership_id
      description: |-
        Updates a user's group membership. Only admins of this
        group or users with admin-level permissions will be able to
        use this API.
    delete:
      summary: Remove user from group
      tags:
        - Remove
        - User
        - From
        - Group
        - Group_memberships
        - Group_membership_id
      description: |-
        Deletes a specific group membership. Only admins of this
        group or users with admin-level permissions will be able to
        u
