openapi: 3.1.0
info:
  title: Box Groups API
paths:
  /groups:
    get:
      summary: List groups for enterprise
      tags:
        - List
        - Groups
        - For
        - Enterprise
        - Groups
      description: |-
        Retrieves all of the groups for a given enterprise. The user
        must have admin permissions to inspect enterprise's groups.
    post:
      summary: Create group
      tags:
        - Create
        - Group
        - Groups
      description: |-
        Creates a new group of users in an enterprise. Only users with admin
        permissions can create new groups.
  /groups/terminate_sessions:
    post:
      summary: Create jobs to terminate user group session
      tags:
        - Create
        - Jobs
        - To
        - Terminate
        - User
        - Group
        - Session
        - Groups
        - Terminate_sessions
      description: |-
        Validates the roles and permissions of the group,
        and creates asynchronous jobs
        to terminate the group's sessions.
        Returns the status for the POST request.
  /groups/{group_id}:
    get:
      summary: Get group
      tags:
        - Get
        - Group
        - Groups
        - Terminate_sessions
        - Group_id
      description: |-
        Retrieves information about a group. Only members of this
        group or users with admin-level permissions will be able to
        use this API.
    put:
      summary: Update group
      tags:
        - Update
        - Group
        - Groups
        - Terminate_sessions
        - Group_id
      description: |-
        Updates a specific group. Only admins of this
        group or users with admin-level permissions will be able to
        use this API.
    delete:
      summary: Remove group
      tags:
        - Remove
        - Group
        - Groups
        - Terminate_sessions
        - Group_id
      description: |-
        Permanently deletes a group. Only users with
        admin-level permissions will be able to use this API.
  /groups/{group_id}/memberships:
    get:
      summary: List members of group
      tags:
        - List
        - Members
        - Of
        - Group
        - Groups
        - Terminate_sessions
        - Group_id
        - Memberships
      description: |-
        Retrieves all the members for a group. Only members of this
        group or users with admin-level permissions will be able to
        use this API.
  /groups/{group_id}/collaborations:
    get:
      summary: List group collaborations
      tags:
        - List
        - Group
        - Collaborations
        - Groups
        - Terminate_sessions
        - Group_id
        - Memberships
        - Collaborations
      description: |-
        Retrieves all the collaborations for a group. The user
        must have admin permissions to inspect enterprise's groups.

        Each collaboration object has details on which files or
        folders the group has access to and wit
