openapi: 3.1.0
info:
  title: Box Legal Hold Policy Assignments API
paths:
  /legal_hold_policy_assignments:
    get:
      summary: List legal hold policy assignments
      tags:
        - List
        - Legal
        - Hold
        - Policy
        - Assignments
        - Legal_hold_policy_assignments
      description: Retrieves a list of items a legal hold policy has been assigned to.
    post:
      summary: Assign legal hold policy
      tags:
        - Assign
        - Legal
        - Hold
        - Policy
        - Legal_hold_policy_assignments
      description: Assign a legal hold to a file, file version, folder, or user.
  /legal_hold_policy_assignments/{legal_hold_policy_assignment_id}:
    get:
      summary: Get legal hold policy assignment
      tags:
        - Get
        - Legal
        - Hold
        - Policy
        - Assignment
        - Legal_hold_policy_assignments
        - Legal_hold_policy_assignment_id
      description: Retrieve a legal hold policy assignment.
    delete:
      tags:
        - Unassign
        - Legal
        - Hold
        - Policy
        - Legal_hold_policy_assignments
        - Legal_hold_policy_assignment_id
      summary: Unassign legal hold policy
      description: |-
        Remove a legal hold from an item.

        This is an asynchronous process. The policy will not be
        fully removed yet when the response returns.
  /legal_hold_policy_assignments/{legal_hold_policy_assignment_id}/files_on_hold:
    get:
      summary: List current file versions for legal hold policy assignment
      tags:
        - List
        - Current
        - File
        - Versions
        - For
        - Legal
        - Hold
        - Policy
        - Assignment
        - Legal_hold_policy_assignments
        - Legal_hold_policy_assignment_id
        - Files_on_hold
      description: >-
        Get a list of current file versions for a legal hold

        assignment.


        In some cases you may want to get previous file versions instead. In
        these

        cases, use the `GET 
        /legal_hold_policy_assignments/:id/file_versions_on_hold`

        API instead to return any previous versions of a file for this legal
        hold

        policy assignment.


        Due to ongoing re-architecture efforts this API might not return all
        file

        versions held for this policy ID. Instead, this API will only return the

        latest file version held in the newly developed architecture. The `GET

        /file_version_legal_holds` API can be used to fetch current and past
        versions

        of files held within the legacy architecture.


        The `GET /legal_hold_policy_assignments?policy_id={id}` API can be used
        to

        find a list of policy assignments for a given policy ID.
  /legal_hold_policy_assignments/{legal_hold_policy_assignment_id}/file_versions_on_hold:
    get:
      summary: List previous file versions for legal hold policy assignment
      tags:
        - List
        - Previous
        - File
        - Versions
        - For
        - Legal
        - Hold
        - Policy
        - Assignment
        - Legal_hold_policy_assignments
        - Legal_hold_policy_assignment_id
        - Files_on_hold
        - File_versions_on_hold
      description: >-
        Get a list of previous file versions for a legal hold

        assignment.


        In some cases you may only need the latest file versions instead. In
        these

        cases, use the `GET  /legal_hold_policy_assignments/:id/files_on_hold`
        API

        instead to return any current (latest) versions of a file for this legal
        hold

        policy assignment.


        Due to ongoing re-architecture efforts this API might not return all
        files

        held for this policy ID. Instead, this API will only return past file
        versions

        held in the newly developed architecture. The `GET
        /file_version_legal_holds`

        API can be used to fetch current and past versions of files held within
        the

        legacy architecture.


        The `GET /legal_hold_policy_assignments?policy_id={id}` API can be used
        to

        find a list of policy assignments for a give
