openapi: 3.1.0
info:
  title: Box Metadata Templates API
paths:
  /metadata_templates:
    get:
      summary: Find metadata template by instance ID
      tags:
        - Find
        - Metadata
        - Template
        - By
        - Instance
        - Metadata_templates
      description: |-
        Finds a metadata template by searching for the ID of an instance of the
        template.
  /metadata_templates/enterprise/securityClassification-6VMVochwUWo/schema:
    get:
      summary: List all classifications
      tags:
        - List
        - All
        - Classifications
        - Metadata_templates
        - Classification
        - Vochw
        - Wo
        - Schema
      description: >-
        Retrieves the classification metadata template and lists all the

        classifications available to this enterprise.


        This API can also be called by including the enterprise ID in the

        URL explicitly, for example

        `/metadata_templates/enterprise_12345/securityClassification-6VMVochwUWo/schema`.
  /metadata_templates/enterprise/securityClassification-6VMVochwUWo/schema#add:
    put:
      summary: Add classification
      tags:
        - Add
        - Classification
        - Metadata_templates
        - Classification
        - Vochw
        - Wo
        - Schema
        - Schema#add
      description: >-
        Adds one or more new classifications to the list of classifications

        available to the enterprise.


        This API can also be called by including the enterprise ID in the

        URL explicitly, for example

        `/metadata_templates/enterprise_12345/securityClassification-6VMVochwUWo/schema`.
  /metadata_templates/enterprise/securityClassification-6VMVochwUWo/schema#update:
    put:
      summary: Update classification
      tags:
        - Update
        - Classification
        - Metadata_templates
        - Classification
        - Vochw
        - Wo
        - Schema
        - Schema#add
        - Schema#update
      description: >-
        Updates the labels and descriptions of one or more classifications

        available to the enterprise.


        This API can also be called by including the enterprise ID in the

        URL explicitly, for example

        `/metadata_templates/enterprise_12345/securityClassification-6VMVochwUWo/schema`.
  /metadata_templates/{scope}/{template_key}/schema:
    get:
      summary: Get metadata template by name
      tags:
        - Get
        - Metadata
        - Template
        - By
        - Name
        - Metadata_templates
        - Classification
        - Vochw
        - Wo
        - Schema
        - Schema#add
        - Schema#update
        - Scope
        - Template_key
      description: >-
        Retrieves a metadata template by its `scope` and `templateKey` values.


        To find the `scope` and `templateKey` for a template, list all templates
        for

        an enterprise or globally, or list all templates applied to a file or
        folder.
    put:
      tags:
        - Update
        - Metadata
        - Template
        - Metadata_templates
        - Classification
        - Vochw
        - Wo
        - Schema
        - Schema#add
        - Schema#update
        - Scope
        - Template_key
      summary: Update metadata template
      description: >-
        Updates a metadata template.


        The metadata template can only be updated if the template

        already exists.


        The update is applied atomically. If any errors occur during the

        application of the operations, the metadata template will not be
        changed.
    delete:
      summary: Remove metadata template
      tags:
        - Remove
        - Metadata
        - Template
        - Metadata_templates
        - Classification
        - Vochw
        - Wo
        - Schema
        - Schema#add
        - Schema#update
        - Scope
        - Template_key
      description: |-
        Delete a metadata template and its instances.
        This deletion is permanent and can not be reversed.
  /metadata_templates/{template_id}:
    get:
      summary: Get metadata template by ID
      tags:
        - Get
        - Metadata
        - Template
        - By
        - Metadata_templates
        - Classification
        - Vochw
        - Wo
        - Schema
        - Schema#add
        - Schema#update
        - Scope
        - Template_key
        - Template_id
      description: Retrieves a metadata template by its ID.
  /metadata_templates/global:
    get:
      summary: List all global metadata templates
      tags:
        - List
        - All
        - Global
        - Metadata
        - Templates
        - Metadata_templates
        - Classification
        - Vochw
        - Wo
        - Schema
        - Schema#add
        - Schema#update
        - Scope
        - Template_key
        - Template_id
        - Global
      description: |-
        Used to retrieve all generic, global metadata templates available to all
        enterprises using Box.
  /metadata_templates/enterprise:
    get:
      summary: List all metadata templates for enterprise
      tags:
        - List
        - All
        - Metadata
        - Templates
        - For
        - Enterprise
        - Metadata_templates
        - Classification
        - Vochw
        - Wo
        - Schema
        - Schema#add
        - Schema#update
        - Scope
        - Template_key
        - Template_id
        - Global
        - Enterprise
      description: >-
        Used to retrieve all metadata templates created to be used specifically
        within

        the user's enterprise
  /metadata_templates/schema:
    post:
      summary: Create metadata template
      tags:
        - Create
        - Metadata
        - Template
        - Metadata_templates
        - Classification
        - Vochw
        - Wo
        - Schema
        - Schema#add
        - Schema#update
        - Scope
        - Template_key
        - Template_id
        - Global
        - Enterprise
      description: |-
        Creates a new metadata template that can be applied to
        files and folders.
  /metadata_templates/schema#classifications:
    post:
      summary: Add initial classifications
      tags:
        - Add
        - Initial
        - Classifications
        - Metadata_templates
        - Classification
        - Vochw
        - Wo
        - Schema
        - Schema#add
        - Schema#update
        - Scope
        - Template_key
        - Template_id
        - Global
        - Enterprise
        - Schema#classifications
      description: |-
        When an enterprise does not yet have any classifications, this API call
        initializes the classification template with an initial set of
        classifications.

        If an enterprise already has a classification, the template will already
        exist and instead an API call should be made to add additional
        clas
