openapi: 3.1.0
info:
  title: Box Metadata Queries API
paths:
  /metadata_queries/execute_read:
    post:
      summary: Query files/folders by metadata
      tags:
        - Query
        - Files/folders
        - By
        - Metadata
        - Metadata_queries
        - Execute_read
      description: >-
        Create a search using SQL-like syntax to return items that match
        specific

        metadata.


        By default, this endpoint returns only the most basic info about the
        items for

        which the query matches. To get additional fields for each item,
        including any

        of the metadata, use the `fields` attribute i
