openapi: 3.1.0
info:
  title: Box Oauth2 API
paths:
  /oauth2/token:
    post:
      summary: Request access token
      description: |-
        Request an Access Token using either a client-side obtained OAuth 2.0
        authorization code or a server-side JWT assertion.

        An Access Token is a string that enables Box to verify that a
        request belongs to an authorized session. In the normal order of
        operations you will begin by requesting authentication from the
        [authorize](#get-authorize) endpoint and Box will send you an
        authorization code.

        You will then send this code to this endpoint to exchange it for
        an Access Token. The returned Access Token can then be used to to make
        Box API calls.
      tags:
        - Request
        - Access
        - Token
        - Oauth2
        - Token
  /oauth2/token#refresh:
    post:
      summary: Refresh access token
      description: Refresh an Access Token using its client ID, secret, and refresh token.
      tags:
        - Refresh
        - Access
        - Token
        - Oauth2
        - Token
        - Token#refresh
  /oauth2/revoke:
    post:
      summary: Revoke access token
      description: |-
        Revoke an active Access Token, effectively logging a user out
        that has been previously authenticated.
      tags:
        - Revoke
        - Access
        - Token
        - Oauth2
        - Token
        - Token#refresh
        - Revo
