openapi: 3.1.0
info:
  title: Box Recent Items API
paths:
  /recent_items:
    get:
      summary: List recently accessed items
      tags:
        - List
        - Recently
        - Accessed
        - Items
        - Recent_items
      description: |-
        Returns information about the recent items accessed
        by a user, either in the last 90 days or up to the last
        1000 ite
