openapi: 3.1.0
info:
  title: Box Retention Policy Assignments API
paths:
  /retention_policy_assignments:
    post:
      summary: Assign retention policy
      tags:
        - Assign
        - Retention
        - Policy
        - Retention_policy_assignments
      description: Assigns a retention policy to an item.
  /retention_policy_assignments/{retention_policy_assignment_id}:
    get:
      summary: Get retention policy assignment
      tags:
        - Get
        - Retention
        - Policy
        - Assignment
        - Retention_policy_assignments
        - Retention_policy_assignment_id
      description: Retrieves a retention policy assignment
    delete:
      summary: Remove retention policy assignment
      tags:
        - Remove
        - Retention
        - Policy
        - Assignment
        - Retention_policy_assignments
        - Retention_policy_assignment_id
      description: |-
        Removes a retention policy assignment
        applied to content.
  /retention_policy_assignments/{retention_policy_assignment_id}/files_under_retention:
    get:
      summary: Get files under retention
      tags:
        - Get
        - Files
        - Under
        - Retention
        - Retention_policy_assignments
        - Retention_policy_assignment_id
        - Files_under_retention
      description: >-
        Returns a list of files under retention for a retention policy
        assignment.
  /retention_policy_assignments/{retention_policy_assignment_id}/file_versions_under_retention:
    get:
      summary: Get file versions under retention
      tags:
        - Get
        - File
        - Versions
        - Under
        - Retention
        - Retention_policy_assignments
        - Retention_policy_assignment_id
        - Files_under_retention
        - File_versions_under_retention
      description: Returns a list of file versions under retention for a retention policy
