openapi: 3.1.0
info:
  title: Box Retention Policies API
paths:
  /retention_policies:
    get:
      summary: List retention policies
      tags:
        - List
        - Retention
        - Policies
        - Retention_policies
      description: Retrieves all of the retention policies for an enterprise.
    post:
      summary: Create retention policy
      tags:
        - Create
        - Retention
        - Policy
        - Retention_policies
      description: Creates a retention policy.
  /retention_policies/{retention_policy_id}:
    get:
      summary: Get retention policy
      tags:
        - Get
        - Retention
        - Policy
        - Retention_policies
        - Retention_policy_id
      description: Retrieves a retention policy.
    put:
      summary: Update retention policy
      tags:
        - Update
        - Retention
        - Policy
        - Retention_policies
        - Retention_policy_id
      description: Updates a retention policy.
    delete:
      summary: Delete retention policy
      tags:
        - Delete
        - Retention
        - Policy
        - Retention_policies
        - Retention_policy_id
      description: Permanently deletes a retention policy.
  /retention_policies/{retention_policy_id}/assignments:
    get:
      summary: List retention policy assignments
      tags:
        - List
        - Retention
        - Policy
        - Assignments
        - Retention_policies
        - Retention_policy_id
        - Assignments
      description: >-
        Returns a list of all retention policy assignments associated with a
        specified

        reten
