openapi: 3.1.0
info:
  title: Box Search API
paths:
  /search:
    get:
      summary: Search for content
      tags:
        - Search
        - For
        - Content
        - Search
      description: |-
        Searches for files, folders, web links, and shared files across the
        users content or across the entire
