openapi: 3.1.0
info:
  title: Box Shared Items API
paths:
  /shared_items:
    get:
      summary: Find file for shared link
      tags:
        - Find
        - File
        - For
        - Shared
        - Link
        - Shared_items
      description: |-
        Returns the file represented by a shared link.

        A shared file can be represented by a shared link,
        which can originate within the current enterprise or within another.

        This endpoint allows an application to retrieve information about a
        shared file when only given a shared link.

        The `shared_link_permission_options` array field can be returned
        by requesting it in the `fields` query parameter.
  /shared_items#folders:
    get:
      summary: Find folder for shared link
      tags:
        - Find
        - Folder
        - For
        - Shared
        - Link
        - Shared_items
        - Shared_items#folders
      description: |-
        Return the folder represented by a shared link.

        A shared folder can be represented by a shared link,
        which can originate within the current enterprise or within another.

        This endpoint allows an application to retrieve information about a
        shared folder when only given a shared link.
  /shared_items#web_links:
    get:
      summary: Find web link for shared link
      tags:
        - Find
        - Web
        - Link
        - For
        - Shared
        - Shared_items
        - Shared_items#folders
        - Shared_items#web_links
      description: |-
        Returns the web link represented by a shared link.

        A shared web link can be represented by a shared link,
        which can originate within the current enterprise or within another.

        This endpoint allows an application to retrieve information about a
        shared web link when only given a 
