openapi: 3.1.0
info:
  title: Box Shield Information Barrier Segment Restrictions API
paths:
  /shield_information_barrier_segment_restrictions/{shield_information_barrier_segment_restriction_id}:
    get:
      summary: Get shield information barrier segment restriction by ID
      tags:
        - Get
        - Shield
        - Information
        - Barrier
        - Segment
        - Restriction
        - By
        - Shield_information_barrier_segment_restrictions
        - Shield_information_barrier_segment_restriction_id
      description: |-
        Retrieves a shield information barrier segment
        restriction based on provided ID.
    delete:
      summary: Delete shield information barrier segment restriction by ID
      tags:
        - Delete
        - Shield
        - Information
        - Barrier
        - Segment
        - Restriction
        - By
        - Shield_information_barrier_segment_restrictions
        - Shield_information_barrier_segment_restriction_id
      description: |-
        Delete shield information barrier segment restriction
        based on provided ID.
  /shield_information_barrier_segment_restrictions:
    get:
      summary: List shield information barrier segment restrictions
      tags:
        - List
        - Shield
        - Information
        - Barrier
        - Segment
        - Restrictions
        - Shield_information_barrier_segment_restrictions
        - Shield_information_barrier_segment_restriction_id
      description: |-
        Lists shield information barrier segment restrictions
        based on provided segment ID.
    post:
      summary: Create shield information barrier segment restriction
      tags:
        - Create
        - Shield
        - Information
        - Barrier
        - Segment
        - Restriction
        - Shield_information_barrier_segment_restrictions
        - Shield_information_barrier_segment_restriction_id
      description: |-
        Creates a shield information barrier
        segment restric
