openapi: 3.1.0
info:
  title: Box Shield Information Barrier Segments API
paths:
  /shield_information_barrier_segments/{shield_information_barrier_segment_id}:
    get:
      summary: Get shield information barrier segment with specified ID
      tags:
        - Get
        - Shield
        - Information
        - Barrier
        - Segment
        - With
        - Specified
        - Shield_information_barrier_segments
        - Shield_information_barrier_segment_id
      description: Retrieves shield information barrier segment based on provided ID..
    delete:
      summary: Delete shield information barrier segment
      tags:
        - Delete
        - Shield
        - Information
        - Barrier
        - Segment
        - Shield_information_barrier_segments
        - Shield_information_barrier_segment_id
      description: |-
        Deletes the shield information barrier segment
        based on provided ID.
    put:
      summary: Update shield information barrier segment with specified ID
      tags:
        - Update
        - Shield
        - Information
        - Barrier
        - Segment
        - With
        - Specified
        - Shield_information_barrier_segments
        - Shield_information_barrier_segment_id
      description: Updates the shield information barrier segment based on provided ID..
  /shield_information_barrier_segments:
    get:
      summary: List shield information barrier segments
      tags:
        - List
        - Shield
        - Information
        - Barrier
        - Segments
        - Shield_information_barrier_segments
        - Shield_information_barrier_segment_id
      description: |-
        Retrieves a list of shield information barrier segment objects
        for the specified Information Barrier ID.
    post:
      summary: Create shield information barrier segment
      tags:
        - Create
        - Shield
        - Information
        - Barrier
        - Segment
        - Shield_information_barrier_segments
        - Shield_information_barrier_segment_id
      description: Creates a shield information bar
