openapi: 3.1.0
info:
  title: Box Shield Information Barrier Reports API
paths:
  /shield_information_barrier_reports:
    get:
      summary: List shield information barrier reports
      tags:
        - List
        - Shield
        - Information
        - Barrier
        - Reports
        - Shield_information_barrier_reports
      description: Lists shield information barrier reports.
    post:
      summary: Create shield information barrier report
      tags:
        - Create
        - Shield
        - Information
        - Barrier
        - Report
        - Shield_information_barrier_reports
      description: Creates a shield information barrier report for a given barrier.
  /shield_information_barrier_reports/{shield_information_barrier_report_id}:
    get:
      summary: Get shield information barrier report by ID
      tags:
        - Get
        - Shield
        - Information
        - Barrier
        - Report
        - By
        - Shield_information_barrier_reports
        - Shield_information_barrier_report_id
      description: Retrieves a shield information barrier repo
