openapi: 3.1.0
info:
  title: Box Shield Information Barrier Segment Members API
paths:
  /shield_information_barrier_segment_members/{shield_information_barrier_segment_member_id}:
    get:
      summary: Get shield information barrier segment member by ID
      tags:
        - Get
        - Shield
        - Information
        - Barrier
        - Segment
        - Member
        - By
        - Shield_information_barrier_segment_members
        - Shield_information_barrier_segment_member_id
      description: |-
        Retrieves a shield information barrier
        segment member by its ID.
    delete:
      summary: Delete shield information barrier segment member by ID
      tags:
        - Delete
        - Shield
        - Information
        - Barrier
        - Segment
        - Member
        - By
        - Shield_information_barrier_segment_members
        - Shield_information_barrier_segment_member_id
      description: |-
        Deletes a shield information barrier
        segment member based on provided ID.
  /shield_information_barrier_segment_members:
    get:
      summary: List shield information barrier segment members
      tags:
        - List
        - Shield
        - Information
        - Barrier
        - Segment
        - Members
        - Shield_information_barrier_segment_members
        - Shield_information_barrier_segment_member_id
      description: |-
        Lists shield information barrier segment members
        based on provided segment IDs.
    post:
      summary: Create shield information barrier segment member
      tags:
        - Create
        - Shield
        - Information
        - Barrier
        - Segment
        - Member
        - Shield_information_barrier_segment_members
        - Shield_information_barrier_segment_member_id
      description: Creates a new shield information barrier seg
