openapi: 3.1.0
info:
  title: Box Sign Templates API
paths:
  /sign_templates:
    get:
      summary: List Box Sign templates
      tags:
        - List
        - Box
        - Sign
        - Templates
        - Sign_templates
      description: Gets Box Sign templates created by a user.
  /sign_templates/{template_id}:
    get:
      summary: Get Box Sign template by ID
      tags:
        - Get
        - Box
        - Sign
        - Template
        - By
        - Sign_templates
        - Template_id
      description: Fetches details of a specific Box Si
