openapi: 3.1.0
info:
  title: Box Skill Invocations API
paths:
  /skill_invocations/{skill_id}:
    put:
      summary: Update all Box Skill cards on file
      tags:
        - Update
        - All
        - Box
        - Skill
        - Cards
        - 'On'
        - File
        - Skill_invocations
        - Skill_id
      description: >-
        An alternative method that can be used to overwrite and update all Box
        Skill

        metadata card
