weekNumber: 12
rules:
  - code: openapi-external-docs-error
    message: External Docs
  - code: openapi-tags-object-error
    message: Tag Object
  - code: openapi-info-contact-error
    message: Contact Object
  - code: openapi-info-license-error
    message: License Object
  - code: openapi-info-terms-of-service-error
    message: Terms of Service
  - code: openapi-info-version-error
    message: Info Version
  - code: openapi-info-title-info
    message: Info Title
  - code: openapi-info-title-upper-case-info
    message: Info Title Upper Case
  - code: openapi-info-description-info
    message: Info Description
  - code: openapi-no-api-in-path-error
    message: No API in Path
  - code: openapi-no-path-trailing-slash-info
    message: Path Trailing Slash
  - code: openapi-path-description-warn
    message: Path Description
  - code: openapi-version-in-path-info
    message: Version in Path
  - code: openapi-operation-security-definitions-error
    message: Operation Security Definition
  - code: openapi-operations-operation-ids-camel-case-error
    message: Operation ID Camel Case
  - code: openapi-operations-operation-ids-info
    message: Operation ID.
  - code: openapi-operations-summary-info
    message: Operation Summary
  - code: openapi-operations-summary-period-none-info
    message: Operation Summary Period
  - code: openapi-operations-tags-info
    message: Operation Tags
  - code: openapi-operations-description-info
    message: Operation Description
  - code: openapi-parameters-name-info
    message: Parameter Name
  - code: openapi-parameters-path-names-camel-case-error
    message: Parameter Path Name Camel Case
  - code: openapi-parameters-description-info
    message: Parameter Description
  - code: openapi-parameters-in-info
    message: Parameters In
  - code: openapi-parameters-required-error
    message: Parameters MUST have a required property.
  - code: openapi-parameters-schema-info
    message: Parameter Schema Type
  - code: openapi-parameters-schema-type-info
    message: Parameter Schema Type
  - code: openapi-request-body-on-put-info
    message: Request Body PUT
  - code: openapi-request-body-content-on-put-info
    message: Request Body Content PUT
  - code: openapi-request-body-have-content-info
    message: Request Body Content
  - code: openapi-request-body-have-application-json-info
    message: Request Body Application JSON
  - code: openapi-request-body-json-media-type-on-put-error
    message: JSON Media Type POSPUTT
  - code: openapi-request-body-json-media-type-on-put-info
    message: JSON Media Type PUT
  - code: openapi-request-body-have-schema-info
    message: Request Body Schema
  - code: openapi-request-body-schema-ref-warn
    message: Request Body Schema Ref
  - code: openapi-request-body-have-schema-properties-warn
    message: Request Body Schema Components
  - code: openapi-request-body-have-schema-required-info
    message: Request Body Schema Required
  - code: openapi-request-body-have-schema-required-warn
    message: Request Body Schema Required
  - code: openapi-request-body-schema-properties-format-error
    message: Request Body Schema Properties Format
  - code: openapi-request-body-schema-properties-names-pascal-case-error
    message: Request Body Schema Property Names Pascal Case
  - code: openapi-request-body-schema-properties-nullable-error
    message: Request Body Schema Properties Format
  - code: openapi-request-body-schema-properties-descriptions-error
    message: Schema Description
  - code: openapi-request-body-schema-properties-descriptions-info
    message: Schema Description
  - code: invalid-ref
    message: '''#/components/schemas/KeywordSkillCard'' does not exist'
  - code: openapi-request-body-schema-properties-names-camel-case-error
    message: Request Body Schema Property Names Camel Case
  - code: openapi-response-put-204-status-code-error
    message: PUT 204 Status Code
  - code: openapi-response-put-500-status-code-error
    message: 500 Status Code for PUT Responses
  - code: openapi-response-put-400-status-code-info
    message: 400 Status Code for PUT Responses
  - code: openapi-response-put-404-status-code-info
    message: 404 Status Code for PUT Responses
  - code: openapi-response-get-default-status-code-info
    message: Response Has Default Status Code
  - code: openapi-response-get-default-content-info
    message: Default Content
  - code: openapi-response-get-default-media-type-info
    message: JSON Media Type Default
  - code: openapi-response-get-default-media-type-schema-info
    message: Schema Default
  - code: openapi-response-get-default-schema-ref-warn
    message: Default Response Schema Ref
  - code: openapi-security-schemes-error
    message: Security Scheme
  - code: openapi-schema-names-camel-case-warn
    message: Schema Name Camel Case
  - code: openapi-schema-names-snake-case-warn
    message: Schema Name Snake Case
  - code: openapi-schema-type-info
    message: Schema Type
  - code: openapi-schema-description-info
    message: Schemas has a description.
  - code: openapi-schema-properties-format-error
    message: Schema Properties Format
  - code: openapi-schema-properties-names-pascal-case-error
    message: Schema Property Names Pascal Case
  - code: openapi-schema-properties-descriptions-error
    message: Schema Description
  - code: openapi-schema-properties-descriptions-info
    message: Schema Description
  - code: openapi-schema-properties-pii-info
    message: Schema PII
  - code: openapi-schema-properties-enum-info
    message: Schema Property Enum
  - code: openapi-schema-properties-enum-casing-error
    message: Schema Property Enum Casing
  - code: openapi-schema-properties-nullable-error
    message: Schema Properties Format
  - code: openapi-schema-properties-type-info
    message: Schema Properties Format
  - code: openapi-schema-properties-names-camel-case-error
    message: Schema Property Names Camel Case
  - code: openapi-schema-properties-nullable-info
    message: Schema Properties Nullable
