openapi: 3.1.0
info:
  title: Box Storage Policies API
paths:
  /storage_policies:
    get:
      summary: List storage policies
      tags:
        - List
        - Storage
        - Policies
        - Storage_policies
      description: Fetches all the storage policies in the enterprise.
  /storage_policies/{storage_policy_id}:
    get:
      summary: Get storage policy
      tags:
        - Get
        - Storage
        - Policy
        - Storage_policies
        - Storage_policy_id
      description: Fetches a specific sto
