openapi: 3.1.0
info:
  title: Box Tasks API
paths:
  /files/{file_id}/tasks:
    get:
      summary: List tasks on file
      description: |-
        Retrieves a list of all the tasks for a file. This
        endpoint does not support pagination.
      tags:
        - List
        - Tasks
        - 'On'
        - File
        - Files
        - File_id
        - Tasks
  /tasks:
    post:
      tags:
        - Create
        - Task
        - Files
        - File_id
        - Tasks
      summary: Create task
      description: >-
        Creates a single task on a file. This task is not assigned to any user
        and

        will need to be assigned separately.
  /tasks/{task_id}:
    get:
      summary: Get task
      tags:
        - Get
        - Task
        - Files
        - File_id
        - Tasks
        - Task_id
      description: Retrieves information about a specific task.
    put:
      tags:
        - Update
        - Task
        - Files
        - File_id
        - Tasks
        - Task_id
      summary: Update task
      description: |-
        Updates a task. This can be used to update a task's configuration, or to
        update its completion state.
    delete:
      tags:
        - Remove
        - Task
        - Files
        - File_id
        - Tasks
        - Task_id
      summary: Remove task
      description: Removes a task from a file.
  /tasks/{task_id}/assignments:
    get:
      summary: List task assignments
      tags:
        - List
        - Task
        - Assignments
        - Files
        - File_id
        - Tasks
        - Task_id
        - Assignments
      description: Lists all of the assignments for a
