openapi: 3.1.0
info:
  title: Box Task Assignments API
paths:
  /task_assignments:
    post:
      summary: Assign task
      tags:
        - Assign
        - Task
        - Task_assignments
      description: |-
        Assigns a task to a user.

        A task can be assigned to more than one user by creating multiple
        assignments.
  /task_assignments/{task_assignment_id}:
    get:
      summary: Get task assignment
      tags:
        - Get
        - Task
        - Assignment
        - Task_assignments
        - Task_assignment_id
      description: Retrieves information about a task assignment.
    put:
      summary: Update task assignment
      tags:
        - Update
        - Task
        - Assignment
        - Task_assignments
        - Task_assignment_id
      description: |-
        Updates a task assignment. This endpoint can be
        used to update the state of a task assigned to a user.
    delete:
      summary: Unassign task
      tags:
        - Unassign
        - Task
        - Task_assignments
        - Task_assignment_id
      description: Deletes a specific task
