openapi: 3.1.0
info:
  title: Box Terms Of Service User Statuses API
paths:
  /terms_of_service_user_statuses:
    get:
      summary: List terms of service user statuses
      tags:
        - List
        - Terms
        - Of
        - Service
        - User
        - Statuses
        - Terms_of_service_user_statuses
      description: |-
        Retrieves an overview of users and their status for a
        terms of service, including Whether they have accepted
        the terms and when.
    post:
      summary: Create terms of service status for new user
      tags:
        - Create
        - Terms
        - Of
        - Service
        - Status
        - For
        - New
        - User
        - Terms_of_service_user_statuses
      description: Sets the status for a terms of service for a user.
  /terms_of_service_user_statuses/{terms_of_service_user_status_id}:
    put:
      summary: Update terms of service status for existing user
      tags:
        - Update
        - Terms
        - Of
        - Service
        - Status
        - For
        - Existing
        - User
        - Terms_of_service_user_statuses
        - Terms_of_service_user_status_id
      description: Updates the status for a terms of service
