openapi: 3.1.0
info:
  title: Box Terms Of Services API
paths:
  /terms_of_services:
    get:
      summary: List terms of services
      tags:
        - List
        - Terms
        - Of
        - Services
        - Terms_of_services
      description: |-
        Returns the current terms of service text and settings
        for the enterprise.
    post:
      tags:
        - Create
        - Terms
        - Of
        - Service
        - Terms_of_services
      summary: Create terms of service
      description: |-
        Creates a terms of service for a given enterprise
        and type of user.
  /terms_of_services/{terms_of_service_id}:
    get:
      summary: Get terms of service
      tags:
        - Get
        - Terms
        - Of
        - Service
        - Terms_of_services
        - Terms_of_service_id
      description: Fetches a specific terms of service.
    put:
      summary: Update terms of service
      tags:
        - Update
        - Terms
        - Of
        - Service
        - Terms_of_services
        - Terms_of_service_id
      description: Updates a specific ter
