openapi: 3.1.0
info:
  title: Box Workflows API
paths:
  /workflows:
    get:
      summary: List workflows
      tags:
        - List
        - Workflows
        - Workflows
      description: >-
        Returns list of workflows that act on a given `folder ID`, and

        have a flow with a trigger type of `WORKFLOW_MANUAL_START`.


        You application must be authorized to use the `Manage Box Relay`
        application

        scope within the developer console in to use this endpoint.
  /workflows/{workflow_id}/start:
    post:
      summary: Starts workflow based on request body
      tags:
        - Starts
        - Workflow
        - Based
        - 'On'
        - Request
        - Body
        - Workflows
        - Workflow_id
        - Start
      description: >-
        Initiates a flow with a trigger type of `WORKFLOW_MANUAL_START`.


        You application must be authorized to use the `Manage Box Relay`
        application

        scope within the develo
