openapi: 3.1.0
info:
  title: Box Zip Downloads API
paths:
  /zip_downloads:
    post:
      summary: Create zip download
      tags:
        - Create
        - Zip
        - Download
        - Zip_downloads
      description: >-
        Creates a request to download multiple files and folders as a single
        `zip`

        archive file. This API does not return the archive but instead performs
        all

        the checks to ensure that the user has access to all the items, and then

        returns a `download_url` and a `status_url` that can be used to download
        the

        archive.


        The limit for an archive is either the Account's upload limit or

        10,000 files, whichever is met first.


        **Note**: Downloading a large file can be

        affected by various

        factors such as distance, network latency,

        bandwidth, and congestion, as well as packet loss

        ratio and current server load.

        For these reasons we recommend that a maximum ZIP archive

        total size does not exceed 25GB.
  /zip_downloads/{zip_download_id}/content:
    get:
      summary: Download zip archive
      tags:
        - Download
        - Zip
        - Archive
        - Zip_downloads
        - Zip_download_id
        - Content
      description: >-
        Returns the contents of a `zip` archive in binary format. This URL does
        not

        require any form of authentication and could be used in a user's browser
        to

        download the archive to a user's device.


        By default, this URL is only valid for a few seconds from the creation
        of

        the request for this archive. Once a download has started it can not be

        stopped and resumed, instead a new request for a zip archive would need
        to

        be created.


        The URL of this endpoint should not be considered as fixed. Instead, use

        the [Create zip download](e://post_zip_downloads) API to request to
        create a

        `zip` archive, and then follow the `download_url` field in the response
        to

        this endpoint.
  /zip_downloads/{zip_download_id}/status:
    get:
      summary: Get zip download status
      tags:
        - Get
        - Zip
        - Download
        - Status
        - Zip_downloads
        - Zip_download_id
        - Content
        - Status
      description: >-
        Returns the download status of a `zip` archive, allowing an application
        to

        inspect the progress of the download as well as the number of items that

        might have been skipped.


        This endpoint can only be accessed once the download has started.

        Subsequently this endpoint is valid for 12 hours from the start of the

        download.


        The URL of this endpoint should not be considered as fixed. Instead, use

        the [Create zip download](e://post_zip_downloads) API to request to
        create a

        `zip` archive, and then follow the `status_url` field in the response to

        th
